
[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 10000
max_test_rejects = 1000000

[invariant]
runs = 256
depth = 15
fail_on_revert = true
